### ISSUE TITLE
Create the logic for a session (login, sign up, logout)

### ISSUE THREAD

**Issue by annaellebgt** [gang21/CS130-Capstone-Project#12]
## User Story
As a user, I would like to be able to connect to my account so that I could play the game based on my progress.

## Detailed Description
Provide additional details and context.
Create a login page so that the user could sign in. 
Create a sign up page
Create a logout button

## Tasks
- #13 
- #17
- #22 

## Acceptance Criteria
- [ ] Given a user with correct credentials , then they can enter the app
- [ ] Given a user with incorrect credentials, then they can't enter the app and are invited to correct them
- [ ] Given a user with incomplete credentials, then  they can't enter the app and are invited to correct them

## Associated Epic
#3
